# Generated by Django 3.2.9 on 2021-12-02 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_app7', '0003_auto_20211202_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 20, 1, 43, 591237, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
