# Generated by Django 3.2.9 on 2021-12-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app6', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='txt',
            new_name='text',
        ),
    ]
