# Generated by Django 3.2.9 on 2021-12-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app8', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
